### ISSUE TITLE
Rename this repository from "lc"

### ISSUE THREAD

**Issue by SeanPrashad** [SeanPrashad/lc#3]
The current repo name, `lc`, was used as it was short and easy for me to `cd` into using [`z` ](https://github.com/agkozak/zsh-z).

For better visibility, we should consider renaming from `lc` to `leetcode-patterns`, `leetcode-study-guide`, `leetcode-pattern-study-guide`, or some other variant that better depicts to users the meaning/usage behind this repo.

**Comment by iadeelzafar** [comment]
`leetcode-patterns`

This looks good.

**Comment by SeanPrashad** [comment]
Repo renamed from `lc` to `leetcode-patterns` now
